[package]
name = "Calculator"
version = "0.1.0"
authors = ["heresh <heresh.ahmadi@edu.sait.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
